### ISSUE TITLE
Why does the client stream binary data to the server? Find alternative solution

### ISSUE THREAD

**Issue by sam-ac-dixon** [sam-ac-dixon/mayhem#10]

**Comment by Alex3k** [comment]
From spending a good few hours this evening investigating this issue. Is quite interesting. Mayhem will be ported to as many platforms as possible, including web. This means Unity compiles all code into js so that it runs on the web. With all other platforms, mono can be used to make it platform independant. This means when writing our network process use we need two parts to it, the ifdef for web and the ifdef for 'all other platforms'. This is viewable within WebSocket.cs.

The ifdef for web uses standard web sockets written in js. This is then used at runtime by the c# code (however this c# would have been converted into JS if its a web build). First of all, I changed the 'all other platforms' ifdef to use strings instead of binary data. This was very easy as the functions are part of the websocket standard and were therefore already implemented within the library (websocket-sharp.dll). Once this built and was tested sucessfully I moved on to the web ifdef. This is where the issues lie.

The web specific networking js code can be found within WebSocket.jslib. This is written within js and just uses plain old web sockets. When converted to using strings instead of bytes, the logic within WebSocket.jslib works perfectly fine and sends/recieves strings perfectly. This was confirmed by using console.log's within the file. 

The issue is when the WebSocket.cs class passes a string as a argument or access the return value of a function from WebSocket.jslib. This string is changed to null. This is as strings can't be marshalled from js to c# and the only way to do it is by converting it to and from bytes. This is as you can only send primitive types (boolean , byte , char , short , int , long , float and double). It seems the best way to communicate between the two is use bytes.

The only option I can see is to send a string to the client, websocket.jslib recieves it, marshalls it to bytes, WebSocket.cs retrieves it from websocket.jslib (in byte array format), marshalls it from bytes to a string and then uses that data to update the game state.

This will be the case regardless of the library we use as we will need to support both js and C# due to supporting web and other platforms. 

HEADS UP: This only affects the web code. The other platform code is happy sendings strings however will need to follow the chosen option to ensure interoperability between all builds.

Conclusion: It seems we are converting to and from bytes regardless of what we do. We have two options (these options assume bidirectional communication between client and server):
1a) Server sends string to client, client recieves string in websocket.jslib, marshalls that to bytes so websocket.cs can read it and and returns it to websocket.cs.
1b) When the client wants to send data to server, it sends the string to websocket.cs which marshalls that to bytes for websocket.jslib which then sends those bytes to the server. The server then converts those bytes to a string.

2a) Server sends bytes to a client. The client recieves the bytes in WebSocket.jslib. It then returns them to WebSocket.cs. WebSocket.cs converts that to a string.
2b) When a client wants to send data to server, it sends the string to websocket.cs, websocket.cs marshalls it to bytes for websocket.jslib which then sends the bytes to the server. The server converts the recieved bytes into a string.

They are pretty much the same thing... I personally like option 2 more.

**Comment by Alex3k** [comment]
This has been completed. See Pull Request #12
